### ISSUE TITLE
Field.test_value with granular constraint check

### ISSUE THREAD

**Issue by roll** [frictionlessdata/jsontableschema-py#103]
# Overview

`goodtables` needs an interface to check value against constraints granulary  and without overhead. So API should be like `Field.test_value(value, constraint=None) -> bool`.

# Tasks

- [x] add `Field.test_value(value, constraint=None) -> bool`
- [x] add `skip_constraints` options to `Field.cast/test_value`
- [x] decide about exposing more constraint exceptions (not only `ConstraintError`) - NOT FOR NOW
